### ISSUE TITLE
Mute/Unmute Audio

### ISSUE THREAD

**Issue by richard-to** [richard-to/too-many-cooks#12]
- A player should be able to mute their audio
- When a player mutes their audio, the player's audio is muted to all other players as well
- Need to figure out how this mechanism will work in the UI

**Comment by elderferreiras** [comment]
I think we can have two buttons, a Mic one and a Volume one, so you can unmute yourself and mute everyone else if you want to.

**Comment by richard-to** [comment]
Yeah having two buttons sounds good.  I don't know how to control volume though. I guess it can be done through the video element.

**Comment by richard-to** [comment]
For now only added mute buttons (no other volume control for now).
