### ISSUE TITLE
Add mouth

### ISSUE THREAD

**Issue by richard-to** [richard-to/too-many-cooks#15]
- Each team must be deliver their burgers to their respective mouth objects
- If the player delivers the correct order to the mouth, they should receive points

**Comment by elderferreiras** [comment]
Will we give one point or it depends on the complexity of the burger?

**Comment by richard-to** [comment]
- Yeah that's a good question. I haven't thought about it. Let's try complexity of the burger.
- I was also trying think if there are bonus points we could add somehow, but starting off with burger complexity is good.
